setup:
  - sudo apt-get -qqq -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
  - sudo apt-get -qqq update -y
  - sudo apt-get -qqq install git wget ssmtp -y
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq install -y debconf-utils
  - sudo debconf-set-selections <<< "'"debconf debconf/frontend select Noninteractive"'"
  - sudo debconf-set-selections <<< "'"mysql-server mysql-server/root_password password {{mysql_pass}}"'"
  - sudo debconf-set-selections <<< "'"mysql-server mysql-server/root_password_again password {{mysql_pass}}"'"

jobs:
  - name: recepie-build
    steps: 
      - name: Install JRE
        run: sudo apt-get install default-jre -y
      - name: Install JDK
        run: sudo apt-get -qqq install openjdk-11-jdk -y
      - name: Install Maven
        run: sudo apt-get -qqq install maven -y ; export PATH=/opt/apache-maven-3.8.4/bin:$PATH   
      - name: Install mysql
        run: sudo apt-get -qqq install -y mysql-server
      - name: Delete old recepie
        run: sudo rm -rf RecepieApp
      - name: Clone the Repository
        run: git clone --recursive https://github.com/anvesh-lp/RecepieApp.git
      - name: Copy patch
        run: sudo cp -rp {{shared_path}}/patch/RecepieApp.patch ~/RecepieApp
      - name: Adding patch for war
        run: cd ~/RecepieApp && git apply --ignore-space-change --ignore-whitespace --ignore-space-change RecepieApp.patch
  
  - name: recepie-test
    buildFileLoc: RecepieApp
    steps: 
      - name: Run the test cases
        run: mvn -f RecepieApp clean test | tee testLogger.txt
      - name: Check build status
        run: grep "'"BUILD FAILURE"'" testLogger.txt && echo "'"Build Failed. Cannot create a WAR file"'"
      - name: Create WAR file
        run: grep "'"BUILD SUCCESS"'" testLogger.txt && mvn -f RecepieApp clean package

  - name: recepie-deploy
    homePage: RecepieApp-0.0.1-SNAPSHOT
    sourceFileLoc: RecepieApp/target/RecepieApp-0.0.1-SNAPSHOT.war
    deployFileLoc: /opt/tomcat/webapps/
    server: tomcat
    port: 8080
    steps:
      - name: Install JRE
        run: sudo apt-get install default-jre -y
      - name: Install JDK
        run: sudo apt-get -qqq install openjdk-11-jdk -y
      - name: Install mysql
        run: sudo apt-get -qqq install -y mysql-server